'use strict';

const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const { readPdfMetadataWithLocalWasm } = require('../src/pdf/browser/pdf-metadata-runtime');

const root = path.resolve(__dirname, '../../..');
const fixtureRoot = path.join(root, 'specs/004-local-pdf-core/fixtures/admission');
const manifest = JSON.parse(fs.readFileSync(path.join(fixtureRoot, 'manifest.json'), 'utf8'));
const fixture = manifest.records.find((item) => item.fixtureId === 'admission-seed-ordinary-minimal-v1');
assert.ok(fixture, 'missing ordinary minimal admission fixture');

const EXPECTED_FIXTURE_SHA256 = 'd88bad0d23edfa87d2ee1dd41f8dc0b3909b8f32d5964e8deb144e87be689207';
const EXPECTED_WASM_SHA256 = 'c0af5a6aca30d7e54a149c3a68e317116ca906d6edc28fd3318b12c7d9478ac8';

function sha256(bytes) { return crypto.createHash('sha256').update(bytes).digest('hex'); }
function exactPackagePaths() { const mainPath = require.resolve('@embedpdf/pdfium'); const packageRoot = path.resolve(path.dirname(mainPath), '..'); return { packageJson: path.join(packageRoot, 'package.json'), wasm: path.join(packageRoot, 'dist/pdfium.wasm') }; }
const { wasm: REAL_WASM_PATH } = exactPackagePaths();
const REAL_WASM_BYTES = fs.readFileSync(REAL_WASM_PATH);
assert.equal(sha256(REAL_WASM_BYTES), EXPECTED_WASM_SHA256, 'unexpected exact local PDFium WASM identity');
function bytesForFixture() { return fs.readFileSync(path.join(root, fixture.repositoryPath)); }
function realInitPdfium() { return require(require.resolve('@embedpdf/pdfium')).init; }
function optionsFor(overrides = {}) { return { bytes: overrides.bytes ?? bytesForFixture(), wasmBinary: overrides.wasmBinary ?? Buffer.from(REAL_WASM_BYTES), initPdfium: overrides.initPdfium ?? realInitPdfium() }; }
test('metadata runtime module exposes only the bounded read function', () => { const runtime = require('../src/pdf/browser/pdf-metadata-runtime'); assert.deepEqual(Reflect.ownKeys(runtime), ['readPdfMetadataWithLocalWasm']); assert.equal(typeof readPdfMetadataWithLocalWasm, 'function'); assert.equal(Object.isFrozen(runtime), true); });
test('metadata runtime source keeps the local-only raw-runtime boundary', () => { const source = fs.readFileSync(path.join(root, 'packages/providers/src/pdf/browser/pdf-metadata-runtime.js'), 'utf8'); assert.match(source, /FPDF_GetMetaText/); assert.match(source, /FPDF_LoadMemDocument/); assert.match(source, /FPDF_CloseDocument/); assert.equal(source.match(/await initPdfium\(/g).length, 1); for (const forbidden of [/require\('@embedpdf\/pdfium'\)/,/FPDF_GetPageCount/,/FPDF_LoadPage/,/FPDFText_LoadPage/,/FPDFText_CountChars/,/FPDFText_GetText/,/FPDFText_HasUnicodeMapError/,/FPDFText_CountRects/,/FPDFText_GetRect/,/FPDFText_FindStart/,/FPDFText_FindNext/,/FPDFText_GetSchCount/,/FPDFText_GetSchResultIndex/,/FPDFText_FindClose/,/FPDFText_GetBoundedText/,/FPDFText_GetCharBox/,/FPDFText_GetFontInfo/,/FPDF_RenderPageBitmap/,/\bWebAssembly\b/,/DEFAULT_PDFIUM_WASM_URL/,/\bfetch\s*\(/,/XMLHttpRequest/,/\bWorker\s*\(/,/importScripts/,/child_process/,/node:fs/,/node:path/,/readFileSync/,/setTimeout\s*\(/,/setInterval\s*\(/,/https?:\/\//,/\bURL\b/,/cdn/i]) assert.doesNotMatch(source, forbidden); });
test('invalid inputs fail before runtime effects', async () => { let initCalls = 0; const initPdfium = async () => { initCalls += 1; throw new Error('runtime must not start'); }; const invalidOptions = [{...optionsFor(),bytes:new Uint8Array(),initPdfium},{...optionsFor(),wasmBinary:new Uint8Array(),initPdfium},{...optionsFor(),initPdfium:null},{...optionsFor(),initPdfium:'x'},{...optionsFor(),bytes:new Proxy(bytesForFixture(),{}),initPdfium}]; for (const options of invalidOptions) await assert.rejects(readPdfMetadataWithLocalWasm(options), TypeError); assert.equal(initCalls,0); });
test('ordinary-minimal fixture reports every tag absent', async () => { const bytes=bytesForFixture(); assert.equal(sha256(bytes),EXPECTED_FIXTURE_SHA256); const wasmBinary=Buffer.from(REAL_WASM_BYTES); const inputBefore=Buffer.from(bytes); const wasmBefore=Buffer.from(wasmBinary); const first=await readPdfMetadataWithLocalWasm(optionsFor({bytes,wasmBinary})); assert.equal(first.openSucceeded,true); assert.deepEqual(first.metadata,{title:null,author:null,subject:null,keywords:null,creator:null,producer:null,creationDate:null,modDate:null}); assert.ok(Object.isFrozen(first)); assert.ok(Object.isFrozen(first.metadata)); const second=await readPdfMetadataWithLocalWasm(optionsFor({bytes,wasmBinary})); assert.deepEqual(second,first); assert.deepEqual(bytes,inputBefore); assert.deepEqual(wasmBinary,wasmBefore); });
test('malformed document fails closed without throwing', async () => { const result=await readPdfMetadataWithLocalWasm(optionsFor({bytes:Buffer.from('metadata malformed probe: not a pdf document')})); assert.equal(result.openSucceeded,false); assert.ok(Number.isSafeInteger(result.pdfiumLastError)); });

function stubInitPdfium(script) { const heap=new Uint8Array(script.heapBytes ?? (1<<20)); const allocSizes=new Map(); let nextPointer=1024; const api={ malloc(bytes){ if (script.onMalloc) script.onMalloc(bytes); const pointer=nextPointer; nextPointer+=bytes+16; allocSizes.set(pointer,bytes); return pointer; }, free(pointer){ if(script.onFree) script.onFree(pointer); if(script.failFree) throw new Error('stub free failure'); } }; return async()=>({ PDFiumExt_Init(){}, FPDF_LoadMemDocument:()=>script.openFails?0:1, FPDF_GetLastError:()=>3, FPDF_GetMetaText:(docHandle,tag,pointer,bufferLength)=>{ if(script.onGetMetaText) script.onGetMetaText(tag,pointer,bufferLength); if(script.failSecondCall && pointer !== 0) throw new Error('stub GetMetaText failure'); const value=(script.values ?? {})[tag] ?? null; const natural=value === null ? 0 : (value.length + 1) * 2; const need=((script.failNeed ?? {})[tag] ?? natural); if(pointer === 0 && bufferLength === 0) return need; const got=((script.failWritten ?? {})[tag] ?? natural); const encoded=Buffer.from(`${value ?? ''}\0`,'utf16le'); heap.set(encoded.subarray(0,Math.min(got,encoded.length)),pointer); return got; }, FPDF_CloseDocument:()=>{ if(script.failCloseDocument) throw new Error('stub CloseDocument failure'); }, FPDF_DestroyLibrary(){}, pdfium:{HEAPU8:heap,wasmExports:api} }); }

test('stub package returns exact positive values with string tags', async()=>{ const seen=[]; const result=await readPdfMetadataWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({values:{Title:'Hello',Author:'A',Producer:'P'},onGetMetaText(tag){seen.push(typeof tag);}})})); assert.equal(result.openSucceeded,true); assert.equal(result.metadata.title,'Hello'); assert.equal(result.metadata.author,'A'); assert.equal(result.metadata.producer,'P'); assert.equal(result.metadata.subject,null); assert.equal(seen.length,11,'two-phase calls for the 3 valued tags plus one absence call each for the other 5'); assert.ok(seen.every((entry) => entry === 'string')); });
test('stub package round-trips non-ASCII metadata exactly', async()=>{ const result=await readPdfMetadataWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({values:{Title:'Sïgnthos ✓ PDF'}})})); assert.equal(result.metadata.title,'Sïgnthos ✓ PDF'); });
test('empty-string metadata reads as explicit absence', async()=>{ const result=await readPdfMetadataWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({values:{Title:''}})})); assert.equal(result.metadata.title,null); });
test('invalid metadata length fails closed', async()=>{ await assert.rejects(readPdfMetadataWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({values:{Title:'x'},failNeed:{Title:-1}})})),/invalid metadata length/); });
test('oversized metadata need rejects before value-buffer malloc', async()=>{ let mallocCalls=0; const initPdfium=stubInitPdfium({values:{Title:'x'},failNeed:{Title:0x100000000},onMalloc(){mallocCalls+=1;}}); await assert.rejects(readPdfMetadataWithLocalWasm(optionsFor({initPdfium})),/allocation bounds/); assert.equal(mallocCalls,1,'only the input-document allocation may occur'); });
test('inconsistent written length fails closed', async()=>{ await assert.rejects(readPdfMetadataWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({values:{Title:'abcd'},failWritten:{Title:2}})})),/inconsistent metadata length/); await assert.rejects(readPdfMetadataWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({values:{Title:'abcd'},failWritten:{Title:12}})})),/inconsistent metadata length/); });
test('metadata-slot extent failure still frees the value buffer', async()=>{ const fixtureBytes=bytesForFixture(); const valuePointer=1040+fixtureBytes.length; const freed=[]; await assert.rejects(readPdfMetadataWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({values:{Title:'abcd'},heapBytes:valuePointer+10-1,onFree(pointer){freed.push(pointer);}})})),/metadata buffer exceeds HEAPU8/); assert.deepEqual(freed,[valuePointer,1024]); });
test('input extent failure still frees the input allocation', async()=>{ const fixtureBytes=bytesForFixture(); const freed=[]; await assert.rejects(readPdfMetadataWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({values:{},heapBytes:1024+fixtureBytes.length-1,onFree(pointer){freed.push(pointer);}})})),/input allocation exceeds HEAPU8/); assert.deepEqual(freed,[1024]); });
test('failed document close aggregates as a cleanup failure', async()=>{ const error=await readPdfMetadataWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({values:{},failCloseDocument:true})})).then(()=>{throw new Error('expected cleanup failure');},failure=>failure); assert.equal(error instanceof AggregateError,true); assert.match(error.errors[0].message,/CloseDocument failed/); });
test('read and cleanup failures aggregate without loss', async()=>{ const error=await readPdfMetadataWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({values:{Title:'ab'},failSecondCall:true,failFree:true})})).then(()=>{throw new Error('expected aggregated failure');},failure=>failure); assert.equal(error instanceof AggregateError,true); assert.equal(error.errors.length,2); assert.equal(error.errors[0] instanceof AggregateError,true); assert.match(error.errors[0].errors[0].message,/stub GetMetaText failure/); assert.match(error.errors[0].errors[1].message,/metadata free failed/); assert.match(error.errors[1].message,/free failed/); });
