'use strict';

const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const { selectPdfPageTextWithLocalWasm } = require('../src/pdf/browser/pdf-text-select-runtime');

const root = path.resolve(__dirname, '../../..');
const fixtureRoot = path.join(root, 'specs/004-local-pdf-core/fixtures/admission');
const manifest = JSON.parse(fs.readFileSync(path.join(fixtureRoot, 'manifest.json'), 'utf8'));
const fixture = manifest.records.find((item) => item.fixtureId === 'admission-seed-ordinary-minimal-v1');
assert.ok(fixture, 'missing ordinary minimal admission fixture');

const EXPECTED_FIXTURE_SHA256 = 'd88bad0d23edfa87d2ee1dd41f8dc0b3909b8f32d5964e8deb144e87be689207';
const EXPECTED_WASM_SHA256 = 'c0af5a6aca30d7e54a149c3a68e317116ca906d6edc28fd3318b12c7d9478ac8';

function sha256(bytes) { return crypto.createHash('sha256').update(bytes).digest('hex'); }
function exactPackagePaths() { const mainPath = require.resolve('@embedpdf/pdfium'); const packageRoot = path.resolve(path.dirname(mainPath), '..'); return { packageJson: path.join(packageRoot, 'package.json'), wasm: path.join(packageRoot, 'dist/pdfium.wasm') }; }
const { wasm: REAL_WASM_PATH } = exactPackagePaths();
const REAL_WASM_BYTES = fs.readFileSync(REAL_WASM_PATH);
assert.equal(sha256(REAL_WASM_BYTES), EXPECTED_WASM_SHA256, 'unexpected exact local PDFium WASM identity');
function bytesForFixture() { return fs.readFileSync(path.join(root, fixture.repositoryPath)); }
function realInitPdfium() { return require(require.resolve('@embedpdf/pdfium')).init; }
function optionsFor(overrides = {}) { return { bytes: overrides.bytes ?? bytesForFixture(), wasmBinary: overrides.wasmBinary ?? Buffer.from(REAL_WASM_BYTES), initPdfium: overrides.initPdfium ?? realInitPdfium(), pageIndex: overrides.pageIndex ?? 0, startIndex: overrides.startIndex ?? 0, selectCount: overrides.selectCount ?? 8, maxRects: overrides.maxRects ?? 16 }; }
test('selection runtime module exposes only the bounded select function', () => { const runtime = require('../src/pdf/browser/pdf-text-select-runtime'); assert.deepEqual(Reflect.ownKeys(runtime), ['selectPdfPageTextWithLocalWasm']); assert.equal(typeof selectPdfPageTextWithLocalWasm, 'function'); assert.equal(Object.isFrozen(runtime), true); });
test('selection runtime source keeps the local-only raw-runtime boundary', () => { const source = fs.readFileSync(path.join(root, 'packages/providers/src/pdf/browser/pdf-text-select-runtime.js'), 'utf8'); assert.match(source, /FPDFText_LoadPage/); assert.match(source, /FPDFText_CountChars/); assert.match(source, /FPDFText_GetText/); assert.match(source, /FPDFText_HasUnicodeMapError/); assert.match(source, /FPDFText_CountRects/); assert.match(source, /FPDFText_GetRect/); assert.match(source, /FPDFText_ClosePage/); assert.equal(source.match(/await initPdfium\(/g).length, 1); for (const forbidden of [/require\('@embedpdf\/pdfium'\)/,/FPDFText_FindStart/,/FPDFText_FindNext/,/FPDFText_FindPrev/,/FPDFText_FindClose/,/FPDFText_GetSchCount/,/FPDFText_GetSchResultIndex/,/FPDFText_GetBoundedText/,/FPDFText_GetCharBox/,/FPDFText_GetFontInfo/,/FPDF_RenderPageBitmap/,/\bWebAssembly\b/,/DEFAULT_PDFIUM_WASM_URL/,/\bfetch\s*\(/,/XMLHttpRequest/,/\bWorker\s*\(/,/importScripts/,/child_process/,/node:fs/,/node:path/,/readFileSync/,/setTimeout\s*\(/,/setInterval\s*\(/,/https?:\/\//,/\bURL\b/,/cdn/i]) assert.doesNotMatch(source, forbidden); });
test('invalid inputs fail before runtime effects', async () => { let initCalls = 0; const initPdfium = async () => { initCalls += 1; throw new Error('runtime must not start'); }; const invalidOptions = [{...optionsFor(),bytes:new Uint8Array(),initPdfium},{...optionsFor(),wasmBinary:new Uint8Array(),initPdfium},{...optionsFor(),initPdfium:null},{...optionsFor(),pageIndex:-1,initPdfium},{...optionsFor(),pageIndex:1.5,initPdfium},{...optionsFor(),pageIndex:'0',initPdfium},{...optionsFor(),startIndex:-1,initPdfium},{...optionsFor(),startIndex:1.5,initPdfium},{...optionsFor(),startIndex:'0',initPdfium},{...optionsFor(),startIndex:null,initPdfium},{...optionsFor(),selectCount:-1,initPdfium},{...optionsFor(),selectCount:2.5,initPdfium},{...optionsFor(),selectCount:'8',initPdfium},{...optionsFor(),selectCount:null,initPdfium},{...optionsFor(),selectCount:0x80000000,initPdfium},{...optionsFor(),maxRects:0,initPdfium},{...optionsFor(),maxRects:-1,initPdfium},{...optionsFor(),maxRects:2.5,initPdfium},{...optionsFor(),maxRects:'16',initPdfium},{...optionsFor(),maxRects:null,initPdfium},{...optionsFor(),maxRects:0x80000000,initPdfium},{...optionsFor(),bytes:new Proxy(bytesForFixture(),{}),initPdfium}]; for (const options of invalidOptions) await assert.rejects(selectPdfPageTextWithLocalWasm(options), TypeError); assert.equal(initCalls,0); });
test('ordinary-minimal fixture selects the full range with one exact rect', async () => { const bytes=bytesForFixture(); assert.equal(sha256(bytes),EXPECTED_FIXTURE_SHA256); const wasmBinary=Buffer.from(REAL_WASM_BYTES); const inputBefore=Buffer.from(bytes); const wasmBefore=Buffer.from(wasmBinary); const first=await selectPdfPageTextWithLocalWasm(optionsFor({bytes,wasmBinary})); assert.equal(first.openSucceeded,true); assert.equal(first.pageIndex,0); assert.equal(first.pageCount,1); assert.equal(first.charCount,8); assert.equal(first.startIndex,0); assert.equal(first.selectCount,8); assert.equal(first.rectCount,1); assert.equal(first.rectsTruncated,false); assert.equal(first.unicodeMapError,false); assert.equal(first.text,'Signthos'); assert.deepEqual(first.rects,[{left:20.58799934387207,top:108.84400177001953,right:66.26000213623047,bottom:97.37200164794922}]); assert.ok(Object.isFrozen(first)); assert.ok(Object.isFrozen(first.rects)); assert.ok(Object.isFrozen(first.rects[0])); const second=await selectPdfPageTextWithLocalWasm(optionsFor({bytes,wasmBinary})); assert.deepEqual(second,first); assert.deepEqual(bytes,inputBefore); assert.deepEqual(wasmBinary,wasmBefore); });
test('ordinary-minimal fixture selects a sub-range with its exact rect', async () => { const result=await selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:4})); assert.equal(result.openSucceeded,true); assert.equal(result.charCount,8); assert.equal(result.startIndex,0); assert.equal(result.selectCount,4); assert.equal(result.text,'Sign'); assert.equal(result.rectCount,1); assert.equal(result.rectsTruncated,false); assert.deepEqual(result.rects,[{left:20.58799934387207,top:108.84400177001953,right:43.23200225830078,bottom:97.37200164794922}]); });
test('empty selection returns empty text and no rects', async () => { const result=await selectPdfPageTextWithLocalWasm(optionsFor({startIndex:8,selectCount:0})); assert.equal(result.openSucceeded,true); assert.equal(result.charCount,8); assert.equal(result.text,''); assert.equal(result.rectCount,0); assert.equal(result.rectsTruncated,false); assert.equal(result.unicodeMapError,false); assert.deepEqual(result.rects,[]); assert.ok(Object.isFrozen(result.rects)); });
test('out-of-range selection rejects without partial output', async () => { await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({startIndex:9,selectCount:0})),RangeError); await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({startIndex:6,selectCount:4})),RangeError); await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:9})),RangeError); });
test('malformed document fails closed without throwing', async () => { const result=await selectPdfPageTextWithLocalWasm(optionsFor({bytes:Buffer.from('text selection malformed probe: not a pdf document')})); assert.equal(result.openSucceeded,false); assert.ok(Number.isSafeInteger(result.pdfiumLastError)); });
test('out-of-range page index rejects without partial output', async () => { await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({pageIndex:99})),RangeError); });

function stubInitPdfium(script) { const heap=new Uint8Array(script.heapBytes ?? (1<<20)); const heapView=new DataView(heap.buffer); const allocSizes=new Map(); let nextPointer=1024; const api={ malloc(bytes){ if (script.onMalloc) script.onMalloc(bytes); const pointer=nextPointer; nextPointer+=bytes+16; allocSizes.set(pointer,bytes); return pointer; }, free(pointer){ if(script.onFree) script.onFree(pointer); if(script.failFree) throw new Error('stub free failure'); if(script.failRectFree && allocSizes.get(pointer)===32) throw new Error('stub rect free failure'); } }; return async()=>({ PDFiumExt_Init(){}, FPDF_LoadMemDocument:()=>script.openFails?0:1, FPDF_GetLastError:()=>3, FPDF_GetPageCount:()=>1, FPDF_LoadPage:()=>1, FPDF_GetPageWidthF:()=>200, FPDF_GetPageHeightF:()=>200, FPDFText_LoadPage:()=>1, FPDFText_CountChars:()=>script.charCount, FPDFText_GetText:(handle,start,count,pointer)=>{ if(script.failGetText) throw new Error('stub GetText failure'); const units=Array.from(script.text.slice(start,start+count)).map(character=>character.codePointAt(0)); for(let index=0;index<units.length;index+=1){ heap[pointer+index*2]=units[index]&0xff; heap[pointer+index*2+1]=(units[index]>>8)&0xff; } return units.length+1; }, FPDFText_HasUnicodeMapError:(handle,index)=>script.mapErrors[index], FPDFText_CountRects:(handle,start,count)=>{ if(script.onCountRects) script.onCountRects(start,count); return script.rectTotal ?? 0; }, FPDFText_GetRect:(handle,rectIndex,leftPointer,topPointer,rightPointer,bottomPointer)=>{ if(script.onGetRect) script.onGetRect(rectIndex); if(script.failGetRectThrow) throw new Error('stub GetRect failure'); if(script.failGetRect) return false; const rect=script.rects[rectIndex]; heapView.setFloat64(leftPointer,rect[0],true); heapView.setFloat64(topPointer,rect[1],true); heapView.setFloat64(rightPointer,rect[2],true); heapView.setFloat64(bottomPointer,rect[3],true); return true; }, FPDFText_ClosePage(){}, FPDF_ClosePage(){}, FPDF_CloseDocument(){}, FPDF_DestroyLibrary(){}, pdfium:{HEAPU8:heap,wasmExports:api} }); }

test('empty page returns empty selection without map error', async()=>{ let countRectCalls=0; let getRectCalls=0; const result=await selectPdfPageTextWithLocalWasm(optionsFor({selectCount:0,initPdfium:stubInitPdfium({charCount:0,text:'',mapErrors:[],rectTotal:0,rects:[],onCountRects(){countRectCalls+=1;},onGetRect(){getRectCalls+=1;}})})); assert.equal(result.openSucceeded,true); assert.equal(result.charCount,0); assert.equal(result.rectCount,0); assert.equal(result.rectsTruncated,false); assert.equal(result.unicodeMapError,false); assert.equal(result.text,''); assert.deepEqual(result.rects,[]); assert.ok(Object.isFrozen(result.rects)); assert.equal(countRectCalls,0); assert.equal(getRectCalls,0); });
test('map error surfaces only over the selected range', async()=>{ const script={charCount:4,text:'abcd',mapErrors:[1,0,0,1],rectTotal:0,rects:[]}; const inside=await selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:1,initPdfium:stubInitPdfium(script)})); assert.equal(inside.unicodeMapError,true); const outside=await selectPdfPageTextWithLocalWasm(optionsFor({startIndex:1,selectCount:2,initPdfium:stubInitPdfium(script)})); assert.equal(outside.text,'bc'); assert.equal(outside.unicodeMapError,false); });
test('invalid per-character map flag fails closed', async()=>{ await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:2,initPdfium:stubInitPdfium({charCount:2,text:'ab',mapErrors:[0,-1],rectTotal:0,rects:[]})})),/invalid unicode-map error flag/); });
test('rect list truncates explicitly at the caller rect budget', async()=>{ let countRectCalls=0; const rects=[[0,10,10,0],[10,10,20,0],[20,10,30,0]]; const result=await selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:4,maxRects:2,initPdfium:stubInitPdfium({charCount:4,text:'abcd',mapErrors:[0,0,0,0],rectTotal:3,rects,onCountRects(start,count){countRectCalls+=1; assert.equal(start,0); assert.equal(count,4);}})})); assert.equal(result.openSucceeded,true); assert.equal(result.rectCount,3); assert.equal(result.rectsTruncated,true); assert.deepEqual(result.rects,[{left:0,top:10,right:10,bottom:0},{left:10,top:10,right:20,bottom:0}]); assert.equal(countRectCalls,1); });
test('unsupported PDFium character count rejects before text-buffer malloc', async()=>{ let mallocCalls=0; const initPdfium=stubInitPdfium({charCount:0x80000000,text:'',mapErrors:[],rectTotal:0,rects:[],onMalloc(){mallocCalls+=1;}}); await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({selectCount:0,initPdfium})),/invalid character count/); assert.equal(mallocCalls,1,'only the input-document allocation may occur'); });
test('maximum PDFium int text buffer is rejected before text-buffer malloc', async()=>{ let mallocCalls=0; const initPdfium=stubInitPdfium({charCount:0x7fffffff,text:'',mapErrors:[],rectTotal:0,rects:[],onMalloc(){mallocCalls+=1;}}); await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({selectCount:0x7fffffff,maxRects:0x7fffffff,initPdfium})),/text buffer size exceeds allocation bounds/); assert.equal(mallocCalls,1,'text-buffer malloc must not run after the document allocation'); });
test('invalid rectangle count rejects before rect-slot malloc', async()=>{ let mallocCalls=0; const initPdfium=stubInitPdfium({charCount:2,text:'ab',mapErrors:[0,0],rectTotal:-1,rects:[],onMalloc(){mallocCalls+=1;}}); await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:2,initPdfium})),/invalid rectangle count/); assert.equal(mallocCalls,2,'only input-document and text-buffer allocations may occur'); });
test('failed rectangle query rejects without partial output', async()=>{ await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:2,initPdfium:stubInitPdfium({charCount:2,text:'ab',mapErrors:[0,0],rectTotal:1,rects:[[0,10,10,0]],failGetRect:true})})),/rectangle query failed/); });
test('invalid rectangle coordinates fail closed', async()=>{ await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:2,initPdfium:stubInitPdfium({charCount:2,text:'ab',mapErrors:[0,0],rectTotal:1,rects:[[5,10,1,0]]})})),/invalid text rectangle/); await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:2,initPdfium:stubInitPdfium({charCount:2,text:'ab',mapErrors:[0,0],rectTotal:1,rects:[[NaN,10,10,0]]})})),/invalid text rectangle/); });
test('extraction and text-cleanup failures aggregate without loss', async()=>{ const error=await selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:2,initPdfium:stubInitPdfium({charCount:2,text:'ab',mapErrors:[0,0],rectTotal:0,rects:[],failGetText:true,failFree:true})})).then(()=>{throw new Error('expected aggregated failure');},failure=>failure); assert.equal(error instanceof AggregateError,true); assert.equal(error.errors.length,2); assert.equal(error.errors[0] instanceof AggregateError,true); assert.match(error.errors[0].errors[0].message,/stub GetText failure/); assert.match(error.errors[0].errors[1].message,/text free failed/); assert.match(error.errors[1].message,/free failed/); });
test('rect-slot extent failure still frees the slot', async()=>{ const fixtureBytes=bytesForFixture(); const textPointer=1040+fixtureBytes.length; const slotPointer=1060+fixtureBytes.length; const freed=[]; await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:1,initPdfium:stubInitPdfium({charCount:1,text:'a',mapErrors:[0],rectTotal:1,rects:[[0,10,10,0]],heapBytes:slotPointer,onFree(pointer){freed.push(pointer);}})})),/rect buffer exceeds HEAPU8/); assert.deepEqual(freed,[textPointer,slotPointer,1024]); });
test('input extent failure still frees the input allocation', async()=>{ const fixtureBytes=bytesForFixture(); const freed=[]; await assert.rejects(selectPdfPageTextWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({charCount:8,text:'Signthos',mapErrors:[0,0,0,0,0,0,0,0],rectTotal:0,rects:[],heapBytes:1024+fixtureBytes.length-1,onFree(pointer){freed.push(pointer);}})})),/input allocation exceeds HEAPU8/); assert.deepEqual(freed,[1024]); });
test('rect-read and rect-cleanup failures aggregate without loss', async()=>{ const error=await selectPdfPageTextWithLocalWasm(optionsFor({startIndex:0,selectCount:2,initPdfium:stubInitPdfium({charCount:2,text:'ab',mapErrors:[0,0],rectTotal:1,rects:[[0,10,10,0]],failGetRectThrow:true,failRectFree:true})})).then(()=>{throw new Error('expected aggregated failure');},failure=>failure); assert.equal(error instanceof AggregateError,true); assert.equal(error.errors.length,2); assert.match(error.errors[0].message,/stub GetRect failure/); assert.match(error.errors[1].message,/rect free failed/); });
