'use strict';

const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const { searchPdfPageTextWithLocalWasm } = require('../src/pdf/browser/pdf-text-search-runtime');

const root = path.resolve(__dirname, '../../..');
const fixtureRoot = path.join(root, 'specs/004-local-pdf-core/fixtures/admission');
const manifest = JSON.parse(fs.readFileSync(path.join(fixtureRoot, 'manifest.json'), 'utf8'));
const fixture = manifest.records.find((item) => item.fixtureId === 'admission-seed-ordinary-minimal-v1');
assert.ok(fixture, 'missing ordinary minimal admission fixture');

const EXPECTED_FIXTURE_SHA256 = 'd88bad0d23edfa87d2ee1dd41f8dc0b3909b8f32d5964e8deb144e87be689207';
const EXPECTED_WASM_SHA256 = 'c0af5a6aca30d7e54a149c3a68e317116ca906d6edc28fd3318b12c7d9478ac8';

function sha256(bytes) { return crypto.createHash('sha256').update(bytes).digest('hex'); }
function exactPackagePaths() { const mainPath = require.resolve('@embedpdf/pdfium'); const packageRoot = path.resolve(path.dirname(mainPath), '..'); return { packageJson: path.join(packageRoot, 'package.json'), wasm: path.join(packageRoot, 'dist/pdfium.wasm') }; }
const { wasm: REAL_WASM_PATH } = exactPackagePaths();
const REAL_WASM_BYTES = fs.readFileSync(REAL_WASM_PATH);
assert.equal(sha256(REAL_WASM_BYTES), EXPECTED_WASM_SHA256, 'unexpected exact local PDFium WASM identity');
function bytesForFixture() { return fs.readFileSync(path.join(root, fixture.repositoryPath)); }
function realInitPdfium() { return require(require.resolve('@embedpdf/pdfium')).init; }
function optionsFor(overrides = {}) { return { bytes: overrides.bytes ?? bytesForFixture(), wasmBinary: overrides.wasmBinary ?? Buffer.from(REAL_WASM_BYTES), initPdfium: overrides.initPdfium ?? realInitPdfium(), pageIndex: overrides.pageIndex ?? 0, query: overrides.query ?? 'Sign', maxMatches: overrides.maxMatches ?? 16 }; }
test('search runtime module exposes only the bounded search function', () => { const runtime = require('../src/pdf/browser/pdf-text-search-runtime'); assert.deepEqual(Reflect.ownKeys(runtime), ['searchPdfPageTextWithLocalWasm']); assert.equal(typeof searchPdfPageTextWithLocalWasm, 'function'); assert.equal(Object.isFrozen(runtime), true); });
test('search runtime source keeps the local-only raw-runtime boundary', () => { const source = fs.readFileSync(path.join(root, 'packages/providers/src/pdf/browser/pdf-text-search-runtime.js'), 'utf8'); assert.match(source, /FPDFText_LoadPage/); assert.match(source, /FPDFText_CountChars/); assert.match(source, /FPDFText_FindStart/); assert.match(source, /FPDFText_FindNext/); assert.match(source, /FPDFText_GetSchCount/); assert.match(source, /FPDFText_GetSchResultIndex/); assert.match(source, /FPDFText_FindClose/); assert.match(source, /FPDFText_ClosePage/); assert.equal(source.match(/await initPdfium\(/g).length, 1); for (const forbidden of [/require\('@embedpdf\/pdfium'\)/,/FPDFText_GetText/,/FPDFText_HasUnicodeMapError/,/FPDFText_CountRects/,/FPDFText_GetRect/,/FPDFText_GetBoundedText/,/FPDFText_GetCharBox/,/FPDFText_GetFontInfo/,/FPDF_RenderPageBitmap/,/\bWebAssembly\b/,/DEFAULT_PDFIUM_WASM_URL/,/\bfetch\s*\(/,/XMLHttpRequest/,/\bWorker\s*\(/,/importScripts/,/child_process/,/node:fs/,/node:path/,/readFileSync/,/setTimeout\s*\(/,/setInterval\s*\(/,/https?:\/\//,/\bURL\b/,/cdn/i]) assert.doesNotMatch(source, forbidden); });
test('invalid inputs fail before runtime effects', async () => { let initCalls = 0; const initPdfium = async () => { initCalls += 1; throw new Error('runtime must not start'); }; const invalidOptions = [{...optionsFor(),bytes:new Uint8Array(),initPdfium},{...optionsFor(),wasmBinary:new Uint8Array(),initPdfium},{...optionsFor(),initPdfium:null},{...optionsFor(),pageIndex:-1,initPdfium},{...optionsFor(),pageIndex:1.5,initPdfium},{...optionsFor(),pageIndex:'0',initPdfium},{...optionsFor(),query:'',initPdfium},{...optionsFor(),query:123,initPdfium},{...optionsFor(),query:null,initPdfium},{...optionsFor(),query:{},initPdfium},{...optionsFor(),query:[],initPdfium},{...optionsFor(),maxMatches:0,initPdfium},{...optionsFor(),maxMatches:-1,initPdfium},{...optionsFor(),maxMatches:2.5,initPdfium},{...optionsFor(),maxMatches:'16',initPdfium},{...optionsFor(),maxMatches:null,initPdfium},{...optionsFor(),maxMatches:0x80000000,initPdfium},{...optionsFor(),bytes:new Proxy(bytesForFixture(),{}),initPdfium}]; for (const options of invalidOptions) await assert.rejects(searchPdfPageTextWithLocalWasm(options), TypeError); assert.equal(initCalls,0); });
test('ordinary-minimal fixture finds the exact Sign match', async () => { const bytes=bytesForFixture(); assert.equal(sha256(bytes),EXPECTED_FIXTURE_SHA256); const wasmBinary=Buffer.from(REAL_WASM_BYTES); const inputBefore=Buffer.from(bytes); const wasmBefore=Buffer.from(wasmBinary); const first=await searchPdfPageTextWithLocalWasm(optionsFor({bytes,wasmBinary})); assert.equal(first.openSucceeded,true); assert.equal(first.pageIndex,0); assert.equal(first.pageCount,1); assert.equal(first.charCount,8); assert.equal(first.queryLength,4); assert.equal(first.matchCount,1); assert.equal(first.matchesTruncated,false); assert.deepEqual(first.matches,[{index:0,length:4}]); assert.ok(Object.isFrozen(first)); assert.ok(Object.isFrozen(first.matches)); assert.ok(Object.isFrozen(first.matches[0])); const second=await searchPdfPageTextWithLocalWasm(optionsFor({bytes,wasmBinary})); assert.deepEqual(second,first); assert.deepEqual(bytes,inputBefore); assert.deepEqual(wasmBinary,wasmBefore); });
test('ordinary-minimal fixture finds the exact thos match', async () => { const result=await searchPdfPageTextWithLocalWasm(optionsFor({query:'thos'})); assert.equal(result.openSucceeded,true); assert.equal(result.queryLength,4); assert.equal(result.matchCount,1); assert.equal(result.matchesTruncated,false); assert.deepEqual(result.matches,[{index:4,length:4}]); });
test('ordinary-minimal fixture reports no match for an absent query', async () => { const result=await searchPdfPageTextWithLocalWasm(optionsFor({query:'ZZZ'})); assert.equal(result.openSucceeded,true); assert.equal(result.queryLength,3); assert.equal(result.matchCount,0); assert.equal(result.matchesTruncated,false); assert.deepEqual(result.matches,[]); assert.ok(Object.isFrozen(result.matches)); });
test('malformed document fails closed without throwing', async () => { const result=await searchPdfPageTextWithLocalWasm(optionsFor({bytes:Buffer.from('text search malformed probe: not a pdf document')})); assert.equal(result.openSucceeded,false); assert.ok(Number.isSafeInteger(result.pdfiumLastError)); });
test('out-of-range page index rejects without partial output', async () => { await assert.rejects(searchPdfPageTextWithLocalWasm(optionsFor({pageIndex:99})),RangeError); });

function stubInitPdfium(script) { const heap=new Uint8Array(script.heapBytes ?? (1<<20)); const allocSizes=new Map(); let nextPointer=1024; const queue=(script.matches ?? []).map((match)=>({index:match.index,length:match.length})); let current=null; const api={ malloc(bytes){ if (script.onMalloc) script.onMalloc(bytes); const pointer=nextPointer; nextPointer+=bytes+16; allocSizes.set(pointer,bytes); return pointer; }, free(pointer){ if(script.onFree) script.onFree(pointer); if(script.failFree) throw new Error('stub free failure'); } }; return async()=>({ PDFiumExt_Init(){}, FPDF_LoadMemDocument:()=>script.openFails?0:1, FPDF_GetLastError:()=>3, FPDF_GetPageCount:()=>1, FPDF_LoadPage:()=>1, FPDF_GetPageWidthF:()=>200, FPDF_GetPageHeightF:()=>200, FPDFText_LoadPage:()=>1, FPDFText_CountChars:()=>script.charCount, FPDFText_FindStart:()=>{ if(script.failFindStart) return 0; return 7; }, FPDFText_FindNext:()=>{ if(script.failFindNextThrow) throw new Error('stub FindNext failure'); if(script.failFindNextFlag) return 1; if(queue.length===0) return false; current=queue.shift(); return true; }, FPDFText_GetSchCount:()=>{ if(script.failSchCount !== undefined) return script.failSchCount; return current.length; }, FPDFText_GetSchResultIndex:()=>{ if(script.failSchIndex !== undefined) return script.failSchIndex; return current.index; }, FPDFText_FindClose:()=>{ if(script.failFindClose) throw new Error('stub FindClose failure'); }, FPDFText_ClosePage(){}, FPDF_ClosePage(){}, FPDF_CloseDocument(){}, FPDF_DestroyLibrary(){}, pdfium:{HEAPU8:heap,wasmExports:api} }); }

test('match list truncates explicitly at the caller match budget', async()=>{ const result=await searchPdfPageTextWithLocalWasm(optionsFor({query:'ab',maxMatches:1,initPdfium:stubInitPdfium({charCount:8,matches:[{index:0,length:2},{index:4,length:2}]})})); assert.equal(result.openSucceeded,true); assert.equal(result.queryLength,2); assert.equal(result.matchCount,1); assert.equal(result.matchesTruncated,true); assert.deepEqual(result.matches,[{index:0,length:2}]); });
test('untruncated match list reports every stub match', async()=>{ const result=await searchPdfPageTextWithLocalWasm(optionsFor({query:'ab',maxMatches:4,initPdfium:stubInitPdfium({charCount:8,matches:[{index:0,length:2},{index:4,length:2}]})})); assert.equal(result.matchCount,2); assert.equal(result.matchesTruncated,false); assert.deepEqual(result.matches,[{index:0,length:2},{index:4,length:2}]); });
test('failed search initialization rejects without partial output', async()=>{ await assert.rejects(searchPdfPageTextWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({charCount:8,failFindStart:true})})),/search initialization failed/); });
test('non-boolean find-next flag fails closed', async()=>{ await assert.rejects(searchPdfPageTextWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({charCount:8,matches:[{index:0,length:2}],failFindNextFlag:true})})),/invalid find-next flag/); });
test('invalid match length fails closed', async()=>{ await assert.rejects(searchPdfPageTextWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({charCount:8,matches:[{index:0,length:2}],failSchCount:0})})),/invalid match length/); });
test('invalid match index fails closed', async()=>{ await assert.rejects(searchPdfPageTextWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({charCount:8,matches:[{index:0,length:2}],failSchIndex:-1})})),/invalid match index/); });
test('out-of-range search match fails closed', async()=>{ await assert.rejects(searchPdfPageTextWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({charCount:8,matches:[{index:7,length:2}]})})),/out-of-range search match/); });
test('unsupported PDFium character count rejects before query-buffer malloc', async()=>{ let mallocCalls=0; const initPdfium=stubInitPdfium({charCount:0x80000000,matches:[],onMalloc(){mallocCalls+=1;}}); await assert.rejects(searchPdfPageTextWithLocalWasm(optionsFor({initPdfium})),/invalid character count/); assert.equal(mallocCalls,1,'only the input-document allocation may occur'); });
test('query-slot extent failure still frees the query buffer', async()=>{ const fixtureBytes=bytesForFixture(); const queryPointer=1040+fixtureBytes.length; const freed=[]; await assert.rejects(searchPdfPageTextWithLocalWasm(optionsFor({query:'ab',initPdfium:stubInitPdfium({charCount:8,matches:[],heapBytes:queryPointer+6-1,onFree(pointer){freed.push(pointer);}})})),/query buffer exceeds HEAPU8/); assert.deepEqual(freed,[queryPointer,1024]); });
test('input extent failure still frees the input allocation', async()=>{ const fixtureBytes=bytesForFixture(); const freed=[]; await assert.rejects(searchPdfPageTextWithLocalWasm(optionsFor({initPdfium:stubInitPdfium({charCount:8,matches:[],heapBytes:1024+fixtureBytes.length-1,onFree(pointer){freed.push(pointer);}})})),/input allocation exceeds HEAPU8/); assert.deepEqual(freed,[1024]); });
test('failed find close aggregates as a cleanup failure', async()=>{ const error=await searchPdfPageTextWithLocalWasm(optionsFor({query:'ab',initPdfium:stubInitPdfium({charCount:8,matches:[{index:0,length:2}],failFindClose:true})})).then(()=>{throw new Error('expected cleanup failure');},failure=>failure); assert.equal(error instanceof AggregateError,true); assert.match(error.errors[0].message,/FindClose failed/); });
test('find and cleanup failures aggregate without loss', async()=>{ const error=await searchPdfPageTextWithLocalWasm(optionsFor({query:'ab',initPdfium:stubInitPdfium({charCount:8,matches:[{index:0,length:2}],failFindNextThrow:true,failFree:true})})).then(()=>{throw new Error('expected aggregated failure');},failure=>failure); assert.equal(error instanceof AggregateError,true); assert.equal(error.errors.length,3); assert.match(error.errors[0].message,/stub FindNext failure/); assert.match(error.errors[1].message,/query free failed/); assert.match(error.errors[2].message,/free failed/); });
